import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="p-4 bg-gray-100 flex gap-4">
          <Link href="/" className="text-gray-900 hover:text-blue-600">Home</Link>
          <Link href="/dashboard" className="text-gray-900 hover:text-blue-600">Dashboard</Link>
          <Link href="/profile" className="text-gray-900 hover:text-blue-600">Profile</Link>
          <Link href="/health" className="text-gray-900 hover:text-blue-600">Health</Link>
          <Link href="/playground" className="text-gray-900 hover:text-blue-600">Playground</Link>
          <Link href="/case-studies/ai-accessibility-auditor" className="text-gray-900 hover:text-blue-600">Case Study</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
